FROM --platform=linux/x86_64 eclipse-temurin:11-jdk
#FROM arm64v8/eclipse-temurin:11-jdk

EXPOSE 8080

RUN mkdir -p /opt/uas/logs/uas-backend
VOLUME /opt/uas/logs/uas-backend

VOLUME /tmp

# Server
ENV PORT="PORT"
# Postgres
ENV POSTGRES_USERNAME="POSTGRES_USERNAME"
ENV POSTGRES_PASSWORD="POSTGRES_PASSWORD"
ENV POSTGRES_URL="POSTGRES_URL"
# Keycloak
ENV KEYCLOAK_SERVER_URI="KEYCLOAK_SERVER_URI"
ENV KEYCLOAK_CLIENT_ID="KEYCLOAK_CLIENT_ID"
ENV KEYCLOAK_CLIENT_SECRET="KEYCLOAK_CLIENT_SECRET"
ENV KEYCLOAK_REALM="KEYCLOAK_REALM"
ENV FRONTEND_KEYCLOAK_CLIENT_ID="FRONTEND_KEYCLOAK_CLIENT_ID"
# Minio
ENV MINIO_SERVER_URI="MINIO_SERVER_URI"
ENV MINIO_ACCESS_KEY="MINIO_ACCESS_KEY"
ENV MINIO_SECRET_KEY="MINIO_SECRET_KEY"

ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java","-cp","app:app/lib/*","ucb.accouting.backend.BackendApplicationKt"]