package ucb.accounting.backend.util

import org.springframework.http.HttpStatus

class ResponseCodeUtil (var httpStatus: HttpStatus, message: String, messageTranslated: String? = null) : Exception(message) {
    companion object {
        fun getResponseInfo(code: String): ResponseCodeUtil {
            return when (code) {
                "200-01" -> ResponseCodeUtil(HttpStatus.OK, "User information retrieved successfully.")
                "200-02" -> ResponseCodeUtil(HttpStatus.OK, "User information has been successfully updated.")
                "200-03" -> ResponseCodeUtil(HttpStatus.OK, "Industries retrieved successfully.")
                "200-04" -> ResponseCodeUtil(HttpStatus.OK, "Business entities retrieved successfully.")
                "200-05" -> ResponseCodeUtil(HttpStatus.OK, "Company information retrieved successfully.")
                "200-06" -> ResponseCodeUtil(HttpStatus.OK, "Company information has been successfully updated.")
                "200-07" -> ResponseCodeUtil(HttpStatus.OK, "Accounting plan retrieved successfully.")
                "200-08" -> ResponseCodeUtil(HttpStatus.OK, "Account group information retrieved successfully.")
                "200-09" -> ResponseCodeUtil(HttpStatus.OK, "Account group information has been successfully updated.")
                "200-10" -> ResponseCodeUtil(HttpStatus.OK, "Account subgroup information retrieved successfully.")
                "200-11" -> ResponseCodeUtil(HttpStatus.OK, "Account subgroup information has been successfully updated.")
                "200-12" -> ResponseCodeUtil(HttpStatus.OK, "Account information retrieved successfully.")
                "200-13" -> ResponseCodeUtil(HttpStatus.OK, "Account information has been successfully updated.")
                "200-14" -> ResponseCodeUtil(HttpStatus.OK, "Subaccount information retrieved successfully.")
                "200-15" -> ResponseCodeUtil(HttpStatus.OK, "Subaccount information has been successfully updated.")
                "200-16" -> ResponseCodeUtil(HttpStatus.OK, "Attachment uploaded successfully.")
                "200-17" -> ResponseCodeUtil(HttpStatus.OK, "File retrieved successfully.")
                "200-18" -> ResponseCodeUtil(HttpStatus.OK, "Picture uploaded successfully.")
                "200-19" -> ResponseCodeUtil(HttpStatus.OK, "Picture retrieved successfully.")
                "200-20" -> ResponseCodeUtil(HttpStatus.OK, "Document types retrieved successfully.")
                "200-21" -> ResponseCodeUtil(HttpStatus.OK, "Report types retrieved successfully.")
                "200-22" -> ResponseCodeUtil(HttpStatus.OK, "Journal book report retrieved successfully.")
                "200-23" -> ResponseCodeUtil(HttpStatus.OK, "General ledger report retrieved successfully.")
                "200-24" -> ResponseCodeUtil(HttpStatus.OK, "Trial balance report retrieved successfully.")
                "200-25" -> ResponseCodeUtil(HttpStatus.OK, "Worksheet report retrieved successfully.")
                "200-26" -> ResponseCodeUtil(HttpStatus.OK, "Income statement report retrieved successfully.")
                "200-27" -> ResponseCodeUtil(HttpStatus.OK, "Balance sheet report retrieved successfully.")
                "200-28" -> ResponseCodeUtil(HttpStatus.OK, "Customer information retrieved successfully.")
                "200-29" -> ResponseCodeUtil(HttpStatus.OK, "Customer information has been successfully updated.")
                "200-30" -> ResponseCodeUtil(HttpStatus.OK, "Supplier information retrieved successfully.")
                "200-31" -> ResponseCodeUtil(HttpStatus.OK, "Supplier information has been successfully updated.")
                "200-32" -> ResponseCodeUtil(HttpStatus.OK, "Sale transaction retrieved successfully.")
                "200-33" -> ResponseCodeUtil(HttpStatus.OK, "Expense transaction retrieved successfully.")
                "200-34" -> ResponseCodeUtil(HttpStatus.OK, "Partner information retrieved successfully.")
                "200-35" -> ResponseCodeUtil(HttpStatus.OK, "Tax types retrieved successfully.")
                "200-36" -> ResponseCodeUtil(HttpStatus.OK, "Taxes associated with sub accounts retrieved successfully.")
                "200-37" -> ResponseCodeUtil(HttpStatus.OK, "Journal entry last number retrieved successfully.")
                "200-38" -> ResponseCodeUtil(HttpStatus.OK, "Sale transaction last number retrieved successfully.")
                "200-39" -> ResponseCodeUtil(HttpStatus.OK, "Sale transaction information retrieved successfully.")
                "200-40" -> ResponseCodeUtil(HttpStatus.OK, "Journal Entry retrieved successfully.")
                "201-01" -> ResponseCodeUtil(HttpStatus.CREATED, "The new accountant user has been successfully created.")
                "201-02" -> ResponseCodeUtil(HttpStatus.CREATED, "The new accounting assistant user has been successfully created.")
                "201-03" -> ResponseCodeUtil(HttpStatus.CREATED, "The new client user has been successfully created.")
                "201-04" -> ResponseCodeUtil(HttpStatus.CREATED, "The new company has been successfully created.")
                "201-05" -> ResponseCodeUtil(HttpStatus.CREATED, "The new account group has been successfully created.")
                "201-06" -> ResponseCodeUtil(HttpStatus.CREATED, "The new account subgroup has been successfully created.")
                "201-07" -> ResponseCodeUtil(HttpStatus.CREATED, "The new account has been successfully created.")
                "201-08" -> ResponseCodeUtil(HttpStatus.CREATED, "The new subaccount has been successfully created.")
                "201-09" -> ResponseCodeUtil(HttpStatus.CREATED, "A journal entry has been successfully created.")
                "201-10" -> ResponseCodeUtil(HttpStatus.CREATED, "The new customer has been successfully created.")
                "201-11" -> ResponseCodeUtil(HttpStatus.CREATED, "A sale transaction has been successfully created.")
                "201-12" -> ResponseCodeUtil(HttpStatus.CREATED, "The new supplier has been successfully created.")
                "201-13" -> ResponseCodeUtil(HttpStatus.CREATED, "An expense transaction has been successfully created.")
                "201-14" -> ResponseCodeUtil(HttpStatus.CREATED, "Tax associated with subaccount has been successfully created.")
                "400-01" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create the accountant user was not provided.")
                "400-02" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create the accounting assistant user was not provided.")
                "400-03" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create the client user was not provided.")
                "400-04" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to update the user information was not provided.")
                "400-05" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create a company was not provided.")
                "400-06" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to update the company information was not provided.")
                "400-07" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create an account group was not provided.")
                "400-08" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to update the account group information was not provided.")
                "400-09" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create an account subgroup was not provided.")
                "400-10" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to update the account subgroup information was not provided.")
                "400-11" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create an account was not provided.")
                "400-12" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to update the account information was not provided.")
                "400-13" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create a subaccount was not provided.")
                "400-14" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to update the subaccount information was not provided.")
                "400-15" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to retrieve the journal book report was not provided.")
                "400-16" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to retrieve the general ledger report was not provided.")
                "400-17" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to retrieve the trial balance report was not provided.")
                "400-18" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to retrieve the worksheet report was not provided.")
                "400-19" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to retrieve the income statement report was not provided.")
                "400-20" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to retrieve the balance sheet report was not provided.")
                "400-21" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The accounting principle of double-entry is not being followed with this accounting entry.")
                "400-22" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create a journal entry was not provided.")
                "400-23" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create a customer was not provided.")
                "400-24" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to update the customer information was not provided.")
                "400-25" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create a sale transaction was not provided.")
                "400-26" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create a supplier was not provided.")
                "400-27" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to update the supplier information was not provided.")
                "400-28" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create an expense transaction was not provided.")
                "400-29" -> ResponseCodeUtil(HttpStatus.BAD_REQUEST, "The required information to create a tax associated with subaccount was not provided.")
                "403-01" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have permission to view user information.")
                "403-02" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have permission to update user information.")
                "403-03" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have permission to view company information.")
                "403-04" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have permission to update company information.")
                "403-05" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have permission to view the accounting plan.")
                "403-06" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to create an account group.")
                "403-07" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the account group.")
                "403-08" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to update the account group.")
                "403-09" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to create an account subgroup.")
                "403-10" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the account subgroup.")
                "403-11" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to update the account subgroup.")
                "403-12" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to create an account.")
                "403-13" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the account.")
                "403-14" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to update the account.")
                "403-15" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to create a subaccount.")
                "403-16" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the subaccount.")
                "403-17" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to update the subaccount.")
                "403-18" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to upload an attachment.")
                "403-19" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have permission to view the attachment.")
                "403-20" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to create a journal entry.")
                "403-21" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to request the journal book report.")
                "403-22" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to request the general ledger report.")
                "403-23" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to request the trial balance report.")
                "403-24" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to request the worksheet book report.")
                "403-25" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to request the income statement report.")
                "403-26" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to request the balance sheet report.")
                "403-27" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to create a customer.")
                "403-28" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the customer.")
                "403-29" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to update the customer.")
                "403-30" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to create a supplier.")
                "403-31" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the supplier.")
                "403-32" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to update the supplier.")
                "403-33" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to create a sale transaction.")
                "403-34" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to create an expense transaction.")
                "403-35" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the sale transaction.")
                "403-36" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the expense transaction.")
                "403-37" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the partner.")
                "403-38" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to create a tax associated with subaccount.")
                "403-39" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the taxes.")
                "403-40" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have permission to create an accounting assistant user.")
                "403-41" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have permission to create a client user.")
                "403-42" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the last journal entry number.")
                "403-43" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the last sale transaction number.")
                "403-44" -> ResponseCodeUtil(HttpStatus.FORBIDDEN, "You don't have the necessary permissions to view the last expense transaction number.")
                "404-01" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "User not found.")
                "404-02" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Accountant user not found.")
                "404-03" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Industry not found.")
                "404-04" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Business entity not found.")
                "404-05" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Company not found.")
                "404-06" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Account category not found.")
                "404-07" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Account group not found.")
                "404-08" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Account subgroup not found.")
                "404-09" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Account not found.")
                "404-10" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Subaccount not found.")
                "404-11" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Attachment not found.")
                "404-12" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Document type not found.")
                "404-13" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "S3 Object not found.")
                "404-14" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Customer not found.")
                "404-15" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Supplier not found.")
                "404-16" -> ResponseCodeUtil(HttpStatus.NOT_FOUND, "Tax type not found.")
                "409-01" -> ResponseCodeUtil(HttpStatus.CONFLICT, "An accountant with the same email address already exists in the system.")
                "409-02" -> ResponseCodeUtil(HttpStatus.CONFLICT, "An accounting assistant with the same email address already exists in the company.")
                "409-03" -> ResponseCodeUtil(HttpStatus.CONFLICT, "A client with the same email address already exists in the company.")
                "409-04" -> ResponseCodeUtil(HttpStatus.CONFLICT, "A journal entry with the same number already exists in the system.")
                "409-05" -> ResponseCodeUtil(HttpStatus.CONFLICT, "A sale transaction with the same number already exists in the system.")
                "409-06" -> ResponseCodeUtil(HttpStatus.CONFLICT, "An expense transaction with the same number already exists in the system.")
                "409-07" -> ResponseCodeUtil(HttpStatus.CONFLICT, "A tax associated with the subaccount already exists in the system.")
                else -> ResponseCodeUtil(HttpStatus.INTERNAL_SERVER_ERROR, "An unexpected error occurred.")
            }
        }
    }
}


